### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by sanj0212** [wrcad/xictools#1]
tried installing in both centos and ubuntu linux.  it fails to install.. 
g++: ../../xt_base/lib/miscutil.a: No such file or directory 
only two rpm were created in created..  one adms and another fasthenry..  no other rpm came..

**Comment by wrcad** [comment]
Yes, the initial check-in required that the directory xt/xt_base/lib
be created by hand, or xt_base and dependencies would not build.  This
should be repaired in the current HEAD.

**Comment by sanj0212** [comment]
when the new version is going to released to rectify the installation issue?  Please consider giving installation steps for Ubuntu Linux as well.
thanks

**Comment by wrcad** [comment]
The master branch is ok now.  Ubuntu is not supported yet, only
rom-based distribs.

**Comment by sanj0212** [comment]
This time 5 rpm got build and they got installed:
  xictools_adms-LinuxRHEL6.x86_64 0:2.3-61            xictools_fastcap-LinuxRHEL6.x86_64 0:2.0-12      
  xictools_fasthenry-LinuxRHEL6.x86_64 0:3.0-13       xictools_mrouter-LinuxRHEL6.x86_64 0:1.2-2       
  xictools_vl-LinuxRHEL6.x86_64 0:4.3-2   
But list is not showing up main xic graphical tools for layout and wrspice.  am I missing something?

thanks

**Comment by sanj0212** [comment]
/usr/local/xictools/bin/  folder content is listed below:
admsXml    capgen     fastcap    fcpp       lstunpack  pipedgen   vl         
busgen     cubegen    fasthenry  lstpack    mrouter    pyragen    zbuf 

where is the main xic program in this list?   I am sure something more is missing..

**Comment by wrcad** [comment]
There should be 8 packages, mozy, wrspice, and xic are missing.

There is an initial effort to separate mozy from the rest, since it
has GNU licensing.  I don't know if this currently works.  If you have
the flag to skip mozy set in the top-level Makefile, this could be the
problem.  Otherwise, some other issue could be causing the mozy build
to fail, which would break xic and wrspice.  If you can find where the
build fails in the build output, that would be helpful.  It builds ok
for me.  I'll check/fix the mozy separability tomorrow.

**Comment by sanj0212** [comment]
yes..  I  commented out mozy while building it.   I reinstalled everything after uncommenting mozi in Makefile.  Everything build fine and There are 8 rpm.  could install and invoke the tool.
Many thanks..

**Comment by sanj0212** [comment]
sorry to ask one more simple question.. which is schematic editor for xictools? how to invoke it?

**Comment by sanj0212** [comment]
Thanks for your support.  I would wish for this tool availability in Ubuntu Linux.

**Comment by wrcad** [comment]
Good, glad to hear you're up and running.  There are some rough edges
currently but things will settle down over time.  Please forward any
comments/questions.

**Comment by wrcad** [comment]
The schematic editor is "electrical mode" in Xic.  Select "Electrical"
in the View menu.

**Comment by wrcad** [comment]
Hi,

The latest xictools check-in includes Ubuntu support, pre-built packages
for Ubuntu-17.10 are available on wrcad.com.
